services:
  ollama:
    image: "ollama/ollama:0.3.10"
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ollama:/root/.ollama
  webui:
    container_name: "open-webui"
    image: "ghcr.io/open-webui/open-webui:main"
    ports:
      - "443:8080"
      - "80:8080"
    volumes:
      - open-webui:/app/backend/data
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  open-webui:
  ollama: